USE [UNIONDEV]
GO

/****** Object:  Table [dbo].[TB_CANDIDATOS]    Script Date: 21/10/2019 22:03:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_CANDIDATOS](
	[CAN_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[CAN_NOME] [varchar](150) NOT NULL,
	[CAN_CPF] [varchar](14) NOT NULL,
	[CAN_NASCIMENTO] [date] NOT NULL,
	[CAN_SEXO] [varchar](10) NOT NULL,
	[CAN_CARGO] [varchar](100) NOT NULL,
	[CAN_SETOR] [varchar](150) NOT NULL,
	[CAN_EMPRESA] [varchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CAN_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


