USE [UNIONDEV]
GO

/****** Object:  Table [dbo].[TB_FUNCIONARIOS]    Script Date: 21/10/2019 22:02:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_FUNCIONARIOS](
	[FUN_CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[FUN_NOME] [varchar](50) NOT NULL,
	[FUN_CPF] [varchar](14) NOT NULL,
	[FUN_DATA_NASCIMENTO] [datetime] NOT NULL,
	[FUN_TELEFONE] [varchar](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[FUN_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


